name: asp_react_postgres

services:
  asp_server:
    # image: ${DOCKER_REGISTRY-}reactapp1server
    build:
      context: .
      dockerfile: ReactApp1.Server/Dockerfile
    container_name: asp_server
    ports:
      - "8070:8080"
      - "8071:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - db
  react_client:
    build:
      context: reactapp1.client
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      #- "5163:5173"
      # - "5164:5174"
        - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: appdb
    environment:
      - "POSTGRES_PASSWORD=11111"
      - "POSTGRES_USER=postgres"
    ports:
      - "5437:5432"